### ISSUE TITLE
Error reading version line when launch kimera_semantics.launch play_bag:=true

### ISSUE THREAD

**Issue by AndrewWilesRG** [MIT-SPARK/Kimera-Semantics#39] opened 2020-09-16 02:04 UTC
dear repository,
I installed kimera-semantics and ros  correctly following the instruction online, when I use the command : roslaunch kimera_semantics_ros kimera_semantic.launch play_bag:=true  ,the error is throwed out: Error reading version line
what's wrong  with this ?
my OS version is :ubunt16.04
ROS version: ros kinetic

**Comment by ToniRV** [comment] 2020-09-16 07:04
I can't reproduce this error, but, alternatively, just play the rosbag in another terminal (and leave play_bag as its default which is `false`). Or do you really need to use the rosbag to play in the same launch file than Kimera-Semantics?

**Comment by ToniRV** [comment] 2020-10-24 21:47
Closing, but feel free to re-open if you still have this error.

**Closed as completed by ToniRV** 2020-10-24 21:47 UTC
